version: "3"

services:
  backend:
    depends_on:
      - db
    build: ./backend
    container_name: workshop_backend
    env_file: ./backend/docker-compose.env
    command: bash ./scripts/run_backend_local.sh
    volumes:
      - ./backend:/src
    ports:
      - "8000:8000"
    restart: "no"

  rabbit:
    image: rabbitmq:3.8
    container_name: workshop_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  celery_worker:
    depends_on:
      - db
      - rabbit
    build: ./backend
    container_name: workshop_celery_worker
    env_file: ./backend/docker-compose.env
    command: celery -A apps.config.celery_settings worker -l info
    volumes:
      - ./backend:/src
    restart: "no"

  celery_flower:
    depends_on:
      - db
      - rabbit
    build: ./backend
    container_name: workshop_celery_flower
    env_file: ./backend/docker-compose.env
    command: celery -A apps.config.celery_settings flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/src
    restart: "no"

  celery_beat:
    depends_on:
      - db
      - rabbit
    build: ./backend
    container_name: workshop_celery_beat
    env_file: ./backend/docker-compose.env
    command: celery -A apps.config.celery_settings beat -l info
    volumes:
      - ./backend:/src
    restart: "no"

  db:
    image: mariadb:10.5
    container_name: workshop_db
    environment:
      MYSQL_ROOT_PASSWORD: my-password
      MYSQL_DATABASE: workshop_database
      MYSQL_USER: workshop_db_user
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    restart: always

volumes:
  mysql_data:
