# Generated by Django 3.1.6 on 2021-02-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'Katze', 'verbose_name_plural': 'Katzen'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Nahrung', 'verbose_name_plural': 'Nahrung'},
        ),
        migrations.AlterModelOptions(
            name='hideout',
            options={'verbose_name': 'Versteck', 'verbose_name_plural': 'Verstecke'},
        ),
        migrations.AddField(
            model_name='cat',
            name='colour',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Weiß'), (2, 'Schwarz'), (3, 'Getigert')], default=3, verbose_name='Farbe'),
        ),
    ]
