# Generated by Django 3.1.6 on 2021-02-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20210217_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='age',
            field=models.PositiveIntegerField(default=7, verbose_name='Alter'),
        ),
    ]
