# Generated by Django 3.1.6 on 2021-02-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_cat_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='favourite_food',
            new_name='favourite_foods',
        ),
    ]
