# Generated by Django 3.1.6 on 2021-02-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_auto_20210217_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='last_time_petted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
